name: Cleanup Old Images

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
      - name: Delete old untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'web-search-mcp'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'

      - name: Delete old development images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'web-search-mcp'
          package-type: 'container'
          min-versions-to-keep: 5
          ignore-versions: '^(latest|v[0-9]+\.[0-9]+\.[0-9]+)$'